name: tiktok
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_meedu: ^9.0.6
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  video_player: ^2.7.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  meedu_lints: ^0.0.6

flutter:
  uses-material-design: true
